export const types = {
    AGREGAR_PARTICIPANTE: 'AGREGAR_PARTICIPANTE',
    ELIMINAR_PARTICIPANTE: 'ELIMINAR_PARTICIPANTE',
    OBTENIENDO_TIPOS_TORNEO: 'OBTENIENDO_TIPOS_TORNEO',
    TIPOS_TORNEO_RECIBIDOS: 'TIPOS_TORNEO_RECIBIDOS',
    ERROR_OBTENIENDO_TIPOS_TORNEO: 'ERROR_OBTENIENDO_TIPOS_TORNEO',
    GUARDAR_TORNEO: 'GUARDAR_TORNEO'
}